/*
This file contains all would-be-magic-strings in the app.
*/

module.exports = {
	// MISC
	FIREBASE: "https://radiant-heat-4485.firebaseio.com/",

	// AUTH ACTIONS
	ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT: "LOGOUT",

	// AUTH STATES
	LOGGED_IN: "LOGGED_IN",
	ANONYMOUS: "ANONYMOUS",
	AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

	// ERROR
	DISPLAY_ERROR: "DISPLAY_ERROR",

	//CHAT
	RECEIVING_COMMENTS: "RECEIVING_COMMENTS",

	//userLsit
	GET_USERS: "GET_USERS"
};
